name: pc-ondra
version: '16.04-0.9'
type: gadget
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
grade: stable
confinement: strict
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    stage-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]

slots:
    aeon-z-wave-g5:
        interface: serial-port
        path: /dev/serial-port-zwave
        usb-vendor: 0x0658
        usb-product: 0x0200
